name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install flake8 coverage bandit

      - name: Run linter
        run: flake8 .

      - name: Run tests and measure coverage
        run: |
          coverage run -m unittest discover
          coverage report

      - name: Run security check
        run: bandit -r .



