name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install flake8 coverage bandit requests Flask

      - name: Run Flask server
        run: |
          nohup python app.py --port=5001 > server.log 2>&1 &
          sleep 15 

      - name: Run linter
        run: flake8 .

      - name: Run tests and measure coverage
        run: |
          coverage run -m unittest discover
          coverage report

      - name: Run security check
        run: bandit -r .
        
      - name: Stop Flask server
        run: |
          pkill -f "python app.py"



